name: Docker Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: drienas/dsg-search-front

    steps:
      - uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}

      - name: Deploy the Docker image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}

      - name: Docker tag latest
        run: docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Docker push latest
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  cloud-update:
    needs: publish
    runs-on: ubuntu-latest

    env:
      PORTAINER_PUSH: ${{ secrets.PORTAINER_PUSH }}

    steps:
      - name: Push new Update to Cloud-Service
        run: curl --request POST --url ${{ env.PORTAINER_PUSH }}
